### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method setWallpaperFromAsset on channel wallpaper_manager)

### ISSUE THREAD

**Issue by editedsix** [AdityaMulgundkar/wallpaper_manager#1]
I am getting this MissingPluginException error while using method setwallpaperfromasset, setwallpaperfromfile works fine, please tell me solution, my device is android running with API 29
![1](https://user-images.githubusercontent.com/38066763/78128505-7d23bb00-742f-11ea-8889-036bde6f91d5.png)

**Comment by AdityaMulgundkar** [comment]
Hi, this was an issue in one of the previous releases. Can you confirm that you have set the version to the latest? 
i.e. in your pubspec.yaml file, you must set it to:
`
wallpaper_manager: ^1.0.5
`

If you're on this version & are still facing the issue, reply back here & I'll look further into it.

**Comment by editedsix** [comment]
wallpaper_manager: ^1.0.5 i am facing issue with latest release.

**Comment by AdityaMulgundkar** [comment]
Please try doing a `flutter clean` in your project directory. In Android Studio, you can do this in the "terminal" tab as well. If not, you can always run it from a command prompt. After cleaning, build the project again. 

If it still doesn't work, I'll need some more data from you in order to reproduce the issue on my end, so attach the following here:

1. `flutter doctor`; just run it in your terminal and upload the output.
2. A screenshot or copy of your pubspec.yaml file.
3. A screenshot of the local copy of package:wallpaper_manage.dart/wallpaper_manager.dart (this file is stored locally on your computer & might have been modified. You can open the file by Control+clicking on the line `import 'package:wallpaper_manager/wallpaper_manager.dart';` in your code on most IDEs)
4. A copy/screenshot of WallpaperManagerPlugin.java, you can find this file from inside your Android Studio project manager > Project > External Libraries > Dart Packages > wallpaper_manager-1.0.5. Right-click on wallpaper_manager-1.0.5 folder and select "Show in Explorer". Navigate to android\src\main\java\com\mulgundkar\wallpaper_manager in this folder & find the Java file.

In case any of this seems too difficult for you, you can upload your code on a fresh repository on your account & I can take a look at it instead.

**Comment by AdityaMulgundkar** [comment]
Hi, @EditedSix  I have updated the plug-in to version 1.0.6 today. You should take a look at it again & let me know if the problem still persists. I'm closing this issue for now. Thank you!

**Comment by ssgd111** [comment]
hi, @AdityaMulgundkar  i have same issue.....i am using Latest Version of wallpaper_manager ^1.0.10.....but still Showing Same issue.....please tell me..how to solve this issue...
